## Load image with software requirements for libnnpdf
image: zaharid/conda-centos

stages:
    - build-deploy

#Set to "true" to upload builds for non-default branches
variables:
  UPLOAD_NON_MASTER: "false"
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "false"
  
## Run the configure and make tests
job2:
    stage: build-deploy
    script:
      - "echo `pwd`"
      - "echo `git describe --tag`"
      - "ls"
      - ".ciscripts/build-deploy.sh"
    variables:
        CONDA_PY: "36"
    artifacts:
        untracked: True