## Load image with software requirements for libnnpdf
image: zaharid/conda-centos

stages:
    - build-deploy

#Set to "true" to upload builds for non-default branches
variables:
  UPLOAD_NON_MASTER: "false"
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  GIT_DEPTH: 1000

## Run the configure and make tests
job1:
    stage: build-deploy
    script:
      - ".ciscripts/build-deploy-linux.sh"
    variables:
        CONDA_PY: "36"
    artifacts:
        untracked: True
job2:
    stage: build-deploy
    script:
      - ".ciscripts/build-deploy-linux.sh"
    variables:
        CONDA_PY: "37"
    artifacts:
        untracked: True
