# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

git:
    depth: 1000

os: osx
osx_image: xcode6.4

env:
  global:
    - CONDAPATH="/Users/travis/miniconda3"
    - OUTPUT_ARCH=osx-64
    - OUTPUT_CHANNEL=conda-pkgs-private
    - UPLOAD_NON_MASTER="false"

  matrix:
    - CONDA_PY=36
    - CONDA_PY=37

before_install:
    # Remove homebrew.
    - brew remove --force  --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

# Need to pin conda build to 3.8 because of:
# https://github.com/conda/conda-build/issues/2841

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      conda update --yes conda

      source /Users/travis/miniconda3/bin/activate root
      conda config --append channels conda-forge
      conda config --add channels https://zigzah.com/static/conda-pkgs/
      conda config --add channels https://zigzah.com/static/conda-pkgs-private/
      conda config --set show_channel_urls true
      conda install --yes conda-build

script:
    - ./.ciscripts/build-deploy-osx.sh


