# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

git:
    depth: 1000

os:
  - osx
  - linux
#Latest Mac image
osx_image: xcode10.2

env:
  global:
    - CONDAPATH="/Users/travis/miniconda3"
    - OUTPUT_ARCH=osx-64
    - OUTPUT_CHANNEL=conda-private
    - UPLOAD_NON_MASTER="false"
    - CONDA_BUILD_SYSROOT="${CONDAPATH}/MacOSX10.9.sdk"

  matrix:
    - CONDA_PY=36
    - CONDA_PY=37

before_install:
    # Remove homebrew.
    - >
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then brew remove --force  --ignore-dependencies $(brew list);
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then brew cleanup -s;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then rm -rf $(brew --cache);
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker pull zaharid/conda-centos;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker run -itd --name build zaharid/conda-centos;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker cp ../nnpdf build:/;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo CONDA_PY=$CONDA_PY >> /root/.bashrc"  ;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo NETRC_FILE=$NETRC_FILE >> /root/.bashrc";
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo NNPDF_SSH_KEY=$NNPDF_SSH_KEY >> /root/.bashrc"  ;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo CI_BUID_REF_NAME=$CI_BUID_REF_NAME >> /root/.bashrc";
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo UPLOAD_NON_MASTER=$UPLOAD_NON_MASTER >> /root/.bashrc";
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo TRAVIS_BRANCH=$TRAVIS_BRANCH >> /root/.bashrc";
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "echo TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH >> /root/.bashrc";
     fi

# Need to pin conda build to 3.8 because of:
# https://github.com/conda/conda-build/issues/2841

install:
    - >
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then MINICONDA_URL="https://repo.continuum.io/miniconda";

     echo "$NETRC_FILE" | base64 --decode > ~/.netrc;
     MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh";
     curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}";
     bash $MINICONDA_FILE -b;
     conda update --yes conda;
     curl -L -O https://data.nnpdf.science/MacOSX10.9.sdk.tar.xz;
     tar xfz MacOSX10.9.sdk.tar.xz -C "${CONDAPATH}";
     source /Users/travis/miniconda3/bin/activate root;
     conda config --append channels conda-forge;
     conda config --add channels https://packages.nnpdf.science/conda;
     conda config --add channels https://packages.nnpdf.science/conda-private;
     conda config --set show_channel_urls true;
     conda install --yes conda-build;
     fi

script:
    - >
     if [[ "$TRAVIS_OS_NAME" == "osx" ]];
     then ./.ciscripts/build-deploy-osx.sh;
     fi
    - >
     if [[ "$TRAVIS_OS_NAME" == "linux" ]];
     then docker exec build bash -c "cd /nnpdf/; .ciscripts/build-deploy-linux.sh";
     fi
