## Load image with software requirements for libnnpdf
image: zaharid/debian-7-dev

stages:
    - build-deploy


#Set to "true" to upload builds for non-default branches
variables:
    UPLOAD_NON_MASTER: "false"

## Run the configure and make tests
job1:
    stage: build-deploy
    script: ".ciscripts/build-deploy.sh"

    #We copy the conda package to the git path to be untracked and
    #then catch it as an "artifact"
    artifacts:
        untracked: True

    #TODO: Do two separate stages when we have a newer version with this
    # implemented (and there are proper docs on how to do it):
    # https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2437
    #
    #
    #No idea why this doesn't work
    #artifacts:
    #    paths:
    #        - /yes/conda-bld/linux-64/


job2:
    stage: build-deploy
    variables:
        NNPDF_USE_DOUBLE: "1"
    script: ".ciscripts/build-deploy.sh"
    only:
        - tags
        - triggers
    artifacts:
        untracked: True
