#
# Configuration file for NNPDF++
#

############################################################
description: NNPDF3.1 NNLO fitted charm global dataset

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
experiments:
# Fixed target DIS
  - experiment: NMC
    datasets:
      - { dataset: NMCPD, frac: 0.5 }
      - { dataset: NMC,   frac: 0.5  }
  - experiment: SLAC
    datasets:
      - { dataset: SLACP, frac: 0.5}
      - { dataset: SLACD, frac: 0.5}
  - experiment: BCDMS
    datasets:
      - { dataset: BCDMSP, frac: 0.5}
      - { dataset: BCDMSD, frac: 0.5}
  - experiment: CHORUS
    datasets:
      - { dataset: CHORUSNU, frac: 0.5}
      - { dataset: CHORUSNB, frac: 0.5}
  - experiment: NTVDMN
    datasets:
      - { dataset: NTVNUDMN, frac: 0.5}
      - { dataset: NTVNBDMN, frac: 0.5}
# EMC F2C data
#  - experiment: EMCF2C
#    datasets:
#      - { dataset: EMCF2C, frac: 1.0}
# HERA data
  - experiment: HERACOMB
    datasets:
      - { dataset: HERACOMBNCEM , frac: 0.5}
      - { dataset: HERACOMBNCEP460, frac: 0.5}
      - { dataset: HERACOMBNCEP575, frac: 0.5}
      - { dataset: HERACOMBNCEP820, frac: 0.5}
      - { dataset: HERACOMBNCEP920, frac: 0.5}
      - { dataset: HERACOMBCCEM , frac: 0.5}
      - { dataset: HERACOMBCCEP , frac: 0.5}
# Combined HERA charm production cross-sections
  - experiment: HERAF2CHARM
    datasets:
      - { dataset: HERAF2CHARM, frac: 0.5}
# F2bottom data
  - experiment: F2BOTTOM
    datasets: 
      - { dataset: H1HERAF2B, frac: 1.0}
      - { dataset: ZEUSHERAF2B, frac: 1.0}
      # Fixed target Drell-Yan
  - experiment: DYE886
    datasets:
      - { dataset: DYE886R, frac: 1.0 }
      - { dataset: DYE886P, frac: 0.5, cfac: [QCD] }
  - experiment: DYE605
    datasets:
      - { dataset: DYE605, frac: 0.5, cfac: [QCD] }
# Tevatron jets and W,Z production
  - experiment: CDF
    datasets:
      - { dataset: CDFZRAP, frac: 1.0, cfac: [QCD] }
      - { dataset: CDFR2KT, frac: 0.5, sys: 10 }
  - experiment: D0
    datasets:
      - { dataset: D0ZRAP, frac: 1.0, cfac: [QCD] }
      - { dataset: D0WEASY, frac: 1.0, cfac: [QCD] }
      - { dataset: D0WMASY, frac: 1.0, cfac: [QCD] }
      # ATLAS
  - experiment: ATLAS
    datasets:
# ATLAS EWK
      - { dataset: ATLASWZRAP36PB,   frac: 1.0, cfac: [QCD] }
      - { dataset: ATLASZHIGHMASS49FB, frac: 1.0, cfac: [QCD] }
      - { dataset: ATLASLOMASSDY11EXT, frac: 1.0, cfac: [QCD] }
      - { dataset: ATLASWZRAP11, frac: 0.5, cfac: [QCD] }
# ATLAS jets            
      - { dataset: ATLASR04JETS36PB, frac: 0.5, sys: 10 }
      - { dataset: ATLASR04JETS2P76TEV, frac: 0.5, sys: 10 }
      - { dataset: ATLAS1JET11, frac: 0.5, sys: 10 }
# ATLAS Z pt    
#      - { dataset: ATLASZPT7TEV,   frac: 0.5, cfac: [QCD,NRM], sys: 10 }
      - { dataset: ATLASZPT8TEVMDIST,   frac: 0.5, cfac: [QCD], sys: 10 }
      - { dataset: ATLASZPT8TEVYDIST,   frac: 0.5, cfac: [QCD], sys: 10 }
# ATLAS top
      - { dataset: ATLASTTBARTOT, frac: 1.0, cfac: [QCD] }
      - { dataset: ATLASTOPDIFF8TEVTRAPNORM, frac: 1.0, cfac: [QCD] }     
# CMS
  - experiment: CMS
    datasets:
# CMS EWK
      - { dataset: CMSWEASY840PB, frac: 1.0, cfac: [QCD] }
      - { dataset: CMSWMASY47FB,  frac: 1.0, cfac: [QCD] }
#      - { dataset: CMSWCHARMTOT,  frac: 1.0 }
#      - { dataset: CMSWCHARMRAT,  frac: 1.0 }
      - { dataset: CMSDY2D11,     frac: 0.5, cfac: [QCD] }
      - { dataset: CMSWMU8TEV,     frac: 1.0, cfac: [QCD] }
# CMS jets
      - { dataset: CMSJETS11,     frac: 0.5, sys: 10 }
      - { dataset: CMS1JET276TEV,     frac: 0.5, sys: 10 }
# CMS Z pt
      - { dataset: CMSZDIFF12,   frac: 1.0, cfac: [QCD,NRM], sys: 10 }
# CMS ttbar      
      - { dataset: CMSTTBARTOT, frac: 1.0, cfac: [QCD] } 
      - { dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0, cfac: [QCD] }
  # LHCb 
  - experiment: LHCb
    datasets:
      - { dataset: LHCBZ940PB, frac: 1.0, cfac: [QCD] }
      - { dataset: LHCBZEE2FB, frac: 1.0, cfac: [QCD] }
      - { dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM,QCD] }
      - { dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM,QCD] }

############################################################
datacuts:
  t0pdfset     : 170206-003 # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum
  combocuts    : NNPDF31             # NNPDF3.0 final kin. cuts
  jetptcut_tev : 0                   # jet pt cut for tevatron
  jetptcut_lhc : 0                   # jet pt cut for lhc
  wptcut_lhc   : 30.0                # Minimum pT for W pT diff distributions
  jetycut_tev  : 1e30                # jet rap. cut for tevatron
  jetycut_lhc  : 1e30                # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut  : 1e30                # jet cfact. cut

############################################################
theory:
  theoryid: 53        # database id

############################################################
fitting:
  seed     : 9453862133528      # set the seed for the random generator
  genrep   : on     # on = generate MC replicas, off = use real data
  rngalgo  : 0      # 0 = ranlux, 1 = cmrg, see randomgenerator.cc
  fitmethod: NGA    # Minimization algorithm
  ngen     : 30000  # Maximum number of generations
  nmutants : 80     # Number of mutants for replica
  paramtype: NN
  nnodes   : [2,5,3,1]

  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      # pos: on for NN squared
      # mutsize: mutation size
      # mutprob: mutation probability
      # smallx, largex: preprocessing ranges
      - { fl: sng, pos: off, mutsize: [15], mutprob: [0.05], smallx: [1.04,1.20], largex: [1.45,2.64] }
      - { fl: g,   pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.82,1.31], largex: [0.20,6.17] }
      - { fl: v,   pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.51,0.71], largex: [1.24,2.80] }
      - { fl: v3,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.23,0.63], largex: [1.02,3.14] }
      - { fl: v8,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.53,0.75], largex: [0.70,3.31] }
      - { fl: t3,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [-0.45,1.41], largex: [1.78,3.21] }
      - { fl: t8,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.49,1.32], largex: [1.42,3.13] }
      - { fl: cp,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [-0.07,1.13], largex: [1.73,7.37] }

############################################################
stopping:
  stopmethod: LOOKBACK  # Stopping method
  lbdelta   : 0         # Delta for look-back stopping
  mingen    : 0         # Minimum number of generations
  window    : 500       # Window for moving average
  minchi2   : 3.5       # Minimum chi2 
  minchi2exp: 6.0       # Minimum chi2 for experiments
  nsmear    : 200       # Smear for stopping
  deltasm   : 200       # Delta smear for stopping
  rv        : 2         # Ratio for validation stopping
  rt        : 0.5       # Ratio for training stopping
  epsilon   : 1e-6      # Gradient epsilon

############################################################
positivity:
  posdatasets:
    - { dataset: POSF2U,   poslambda: 1e6 }  # Positivity Lagrange Multiplier
    - { dataset: POSF2DW,  poslambda: 1e6 }
    - { dataset: POSF2S,   poslambda: 1e6 }
    - { dataset: POSFLL,   poslambda: 1e6 }
    - { dataset: POSDYU,   poslambda: 1e10 }
    - { dataset: POSDYD,   poslambda: 1e10 }
    - { dataset: POSDYS,   poslambda: 1e10 }

############################################################
closuretest:
  filterseed  : 0   # Random seed to be used in filtering data partitions
  fakedata    : off # on = to use FAKEPDF to generate pseudo-data
  fakepdf     : MSTW2008nlo68cl # Theory input for pseudo-data
  errorsize   : 1.0 # uncertainties rescaling
  fakenoise   : off # on = to add random fluctuations to pseudo-data
  rancutprob  : 1.0 # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: off # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: off # To print info on PDFs during minimization

############################################################
lhagrid:
  nx  : 150
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq  : 50
  qmax: 1e5

############################################################
debug: false
