#
# Configuration file for NNPDF++
#

############################################################
description: Configuration file for final NLO NNPDF3.0 global fit

############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
experiments:
  # Fixed target DIS
  - experiment: NMC
    datasets:
      - { dataset: NMCPD, frac: 0.5, sys: 3 }
      - { dataset: NMC,   frac: 0.5, sys: 3 }
  - experiment: SLAC
    datasets:
      - { dataset: SLACP, frac: 0.5, sys: 3 }
      - { dataset: SLACD, frac: 0.5, sys: 3 }
  - experiment: BCDMS
    datasets:
      - { dataset: BCDMSP, frac: 0.5, sys: 3 }
      - { dataset: BCDMSD, frac: 0.5, sys: 3 }
  - experiment: CHORUS
    datasets:
      - { dataset: CHORUSNU, frac: 0.5, sys: 3 }
      - { dataset: CHORUSNB, frac: 0.5, sys: 3 }
  - experiment: NTVDMN
    datasets:
      - { dataset: NTVNUDMN, frac: 0.5, sys: 3 }
      - { dataset: NTVNBDMN, frac: 0.5, sys: 3 }
  # HERA data
  - experiment: HERA1AV
    datasets:
      - { dataset: HERA1NCEP, frac: 0.5, sys: 2 }
      - { dataset: HERA1NCEM, frac: 0.5, sys: 2 }
      - { dataset: HERA1CCEP, frac: 0.5, sys: 2 }
      - { dataset: HERA1CCEM, frac: 0.5, sys: 2 }
  # HERA-II data
  - experiment: ZEUSHERA2
    datasets:
      - { dataset: Z06NC, frac: 0.5, sys: 2 }
      - { dataset: Z06CC, frac: 0.5, sys: 2 }
      - { dataset: ZEUSHERA2NCP, frac: 0.5, sys: 2 }
      - { dataset: ZEUSHERA2CCP, frac: 0.5, sys: 2 }
  - experiment: H1HERA2
    datasets:
      - { dataset: H1HERA2NCEM,  frac: 0.5, sys: 2 }
      - { dataset: H1HERA2NCEP,  frac: 0.5, sys: 2 }
      - { dataset: H1HERA2CCEM,  frac: 1.0, sys: 2 }
      - { dataset: H1HERA2CCEP,  frac: 1.0, sys: 2 }
      - { dataset: H1HERA2LOWQ2, frac: 0.5, sys: 2 }
      - { dataset: H1HERA2HGHY,  frac: 0.5, sys: 2 }
  # Combined HERA charm production cross-sections
  - experiment: HERAF2CHARM
    datasets:
      - { dataset: HERAF2CHARM, frac: 0.5, sys: 2 }
      # Fixed target Drell-Yan
  - experiment: DYE886
    datasets:
      - { dataset: DYE886R, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: DYE886P, frac: 0.5, sys: 2 , cfac: [QCD] }
  - experiment: DYE605
    datasets:
      - { dataset: DYE605, frac: 0.5, sys: 2 , cfac: [QCD] }
      # Tevatron jets and W,Z production
  - experiment: CDF
    datasets:
      - { dataset: CDFZRAP, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: CDFR2KT, frac: 0.5, sys: 2 , cfac: [QCD] }
  - experiment: D0
    datasets:
      - { dataset: D0ZRAP, frac: 1.0, sys: 2 , cfac: [QCD] }
      # ATLAS
  - experiment: ATLAS
    datasets:
      - { dataset: ATLASWZRAP36PB,   frac: 1.0, sys: 2, cfac: [QCD,EWK] }
      - { dataset: ATLASR04JETS36PB, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: ATLASR04JETS2P76TEV, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: ATLASZHIGHMASS49FB, frac: 1.0, sys: 2, cfac: [QCD,EWK] }
  # CMS
  - experiment: CMS
    datasets:
      - { dataset: CMSWEASY840PB, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: CMSWMASY47FB,  frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: CMSJETS11,     frac: 0.5, sys: 2 , cfac: [QCD] }
      - { dataset: CMSWCHARMTOT,  frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: CMSWCHARMRAT,  frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: CMSDY2D11,     frac: 0.5, sys: 2, cfac: [QCD,EWK] }
  # LHCb
  - experiment: LHCb
    datasets:
      - { dataset: LHCBW36PB, frac: 1.0, sys: 2 , cfac: [QCD] }
      - { dataset: LHCBZ940PB, frac: 1.0, sys: 2, cfac: [QCD,EWK] }
  # Top
  - experiment: TOP
    datasets:
      - { dataset: TTBARTOT, frac: 1.0, sys: 2 , cfac: [QCD] }

############################################################
datacuts:
  t0pdfset     : NNPDF30_nlo_as_0118 # PDF set to generate t0 covmat
  q2min        : 3.49                # Q2 minimum
  w2min        : 12.5                # W2 minimum
  combocuts    : NNPDF30             # NNPDF3.0 final kin. cuts

############################################################
theory:
  theoryid: 3       # database id

############################################################
fitting:
  seed     : 0      # set the seed for the random generator
  genrep   : on     # on = generate MC replicas, off = use real data
  rngalgo  : 0      # 0 = ranlux, 1 = cmrg, see randomgenerator.cc
  fitmethod: NGA    # Minimization algorithm
  ngen     : 30000  # Maximum number of generations
  nmutants : 80     # Number of mutants for replica
  paramtype: NN
  nnodes   : [2,5,3,1]

  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: EVOL # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      # pos: on for NN squared
      # mutsize: mutation size
      # mutprob: mutation probability
      # smallx, largex: preprocessing ranges
      - { fl: sng, pos: off, mutsize: [15], mutprob: [0.05], smallx: [1.00,1.25], largex: [1.27,2.83] }
      - { fl: g,   pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.91,1.44], largex: [0.25,5.40] }
      - { fl: v,   pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.51,0.75], largex: [1.22,2.94] }
      - { fl: v3,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.34,0.68], largex: [1.35,3.31] }
      - { fl: v8,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.52,0.76], largex: [0.87,3.14] }
      - { fl: t3,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [-0.27,1.35], largex: [1.52,3.21] }
      - { fl: t8,  pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.53,1.44], largex: [1.00,3.54] }

############################################################
stopping:
  stopmethod: LOOKBACK  # Stopping method
  lbdelta   : 0         # Delta for look-back stopping
  mingen    : 0         # Minimum number of generations
  window    : 500       # Window for moving average
  minchi2   : 3.5	# Minimum chi2 
  minchi2exp: 6.0       # Minimum chi2 for experiments
  nsmear    : 200	# Smear for stopping
  deltasm   : 200	# Delta smear for stopping
  rv        : 2         # Ratio for validation stopping
  rt        : 0.5	# Ratio for training stopping
  epsilon   : 1e-6      # Gradient epsilon

############################################################
positivity:
  posdatasets:
    - { dataset: POSF2U,   poslambda: 1e6 }  # Positivity Lagrange Multiplier
    - { dataset: POSF2DW,  poslambda: 1e6 }
    - { dataset: POSF2S,   poslambda: 1e6 }
    - { dataset: POSFLL,   poslambda: 1e6 }
    - { dataset: POSDYU,   poslambda: 1e10 }
    - { dataset: POSDYD,   poslambda: 1e10 }
    - { dataset: POSDYS,   poslambda: 1e10 }
    - { dataset: HIGGSPOS, poslambda: 1e13 }

############################################################
closuretest:
  filterseed  : 0   # Random seed to be used in filtering data partitions
  fakedata    : off # on = to use FAKEPDF to generate pseudo-data
  fakepdf     : MSTW2008nlo68cl # Theory input for pseudo-data
  errorsize   : 1.0 # uncertainties rescaling
  fakenoise   : off # on = to add random fluctuations to pseudo-data
  rancutprob  : 1.0 # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: off # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: off # To print info on PDFs during minimization

############################################################
lhagrid:
  nx  : 100
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq  : 50
  qmax: 1e5

############################################################
debug: off
