#
# Configuration file for NNPDF++
#
############################################################
description: NNPDF4.0 candidate - NLO - fitted charm
############################################################
# frac: training fraction
# ewk: apply ewk k-factors
# sys: systematics treatment (see systypes)
experiments:
# Fixed target DIS
- experiment: NMC
  datasets:
  - {dataset: NMCPD, frac: 0.5}
  - {dataset: NMC, frac: 0.5}
- experiment: SLAC
  datasets:
  - {dataset: SLACP, frac: 0.5}
  - {dataset: SLACD, frac: 0.5}
- experiment: BCDMS
  datasets:
  - {dataset: BCDMSP, frac: 0.5}
  - {dataset: BCDMSD, frac: 0.5}
- experiment: CHORUS
  datasets:
  - {dataset: CHORUSNUPb, frac: 0.5}
  - {dataset: CHORUSNBPb, frac: 0.5}
- experiment: NTVDMN
  datasets:
  - {dataset: NTVNUDMNFe, frac: 0.5}
  - {dataset: NTVNBDMNFe, frac: 0.5}
# HERA data
- experiment: HERACOMB
  datasets:
  - {dataset: HERACOMBNCEM, frac: 0.5}
  - {dataset: HERACOMBNCEP460, frac: 0.5}
  - {dataset: HERACOMBNCEP575, frac: 0.5}
  - {dataset: HERACOMBNCEP820, frac: 0.5}
  - {dataset: HERACOMBNCEP920, frac: 0.5}
  - {dataset: HERACOMBCCEM, frac: 0.5}
  - {dataset: HERACOMBCCEP, frac: 0.5}
# Combined HERA charm production cross-sections
- experiment: HERAF2CHARM
  datasets:
  - {dataset: HERACOMB_SIGMARED_C, frac: 0.5}
# Combined HERA bottom production cross-sections
- experiment: HERAF2BOTTOM
  datasets:
  - {dataset: HERACOMB_SIGMARED_B, frac: 0.5}
# Fixed target Drell-Yan
- experiment: DYE886
  datasets:
  - {dataset: DYE886R, frac: 1.0}
  - {dataset: DYE886P, frac: 0.5}
- experiment: DYE605
  datasets:
  - {dataset: DYE605, frac: 0.5}
# Tevatron jets and W,Z production
- experiment: CDF
  datasets:
  - {dataset: CDFZRAP, frac: 1.0}
- experiment: D0
  datasets:
  - {dataset: D0ZRAP, frac: 1.0}
  - {dataset: D0WEASY, frac: 1.0}
  - {dataset: D0WMASY, frac: 1.0}
# ATLAS
- experiment: ATLAS
  datasets:
  #EWK
  - {dataset: ATLASWZRAP36PB, frac: 1.0} 
  - {dataset: ATLASZHIGHMASS49FB, frac: 1.0}
  - {dataset: ATLASLOMASSDY11EXT, frac: 1.0}
  - {dataset: ATLASWZRAP11, frac: 0.5}
  - {dataset: ATLASWZRAP11CC, frac: 0.5}
  - {dataset: ATLASWZRAP11CF, frac: 0.5}
  - {dataset: ATLAS_WZ_TOT_13TEV, frac: 1.0, cfac: [NRM,EWK]}
  - {dataset: ATLAS_WP_JET_8TEV_PT, frac: 0.5}
  - {dataset: ATLAS_WM_JET_8TEV_PT, frac: 0.5}
#  - {dataset: ATLAS_WP_JET_8TEV_PTJ, frac: 0.5}
#  - {dataset: ATLAS_WM_JET_8TEV_PTJ, frac: 0.5}
  - {dataset: ATLAS_WCHARM_WP_DIFF_7TEV, frac: 1.0}
  - {dataset: ATLAS_WCHARM_WM_DIFF_7TEV, frac: 1.0}
  #Z pT
  - {dataset: ATLASZPT8TEVMDIST, frac: 0.5}
  - {dataset: ATLASZPT8TEVYDIST, frac: 0.5}
  #SINGLE JETS
#  - {dataset: ATLAS1JET11_NEW_SCALE, frac: 0.5, cfac: [EWK]}
  - {dataset: ATLAS_1JET_8TEV_R06, frac: 0.5, cfac: [EWK]}
  #DIJETS
  - {dataset: ATLAS_2JET_7TEV_R06, frac: 0.5, cfac: [EWK]}
  #DIRECT PHOTON
  - {dataset: ATLASPHT12, frac: 0.5, cfac: [NRM,EWK]}
  - {dataset: ATLASPHT15, frac: 0.5, cfac: [EWK]}
  #TOP PAIR
  - {dataset: ATLASTTBARTOT, frac: 1.0}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TPTNORM, frac: 1.0}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TRAPNORM, frac: 1.0}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTRAPNORM, frac: 1.0}
  - {dataset: ATLAS_TTB_DIFF_8TEV_LJ_TTMNORM, frac: 1.0}
  - {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTRAPNORM, frac: 1.0}
#  - {dataset: ATLAS_TOPDIFF_DILEPT_8TEV_TTMNORM, frac: 1.0}
  #SINGLE TOP
  - {dataset: ATLAS_SINGLETOP_TCH_R_7TEV, frac: 1.0}
  - {dataset: ATLAS_SINGLETOP_TCH_R_13TEV, frac: 1.0}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_T_RAP_NORM, frac: 1.0}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_7TEV_TBAR_RAP_NORM, frac: 1.0}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_PT}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_PT}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_PT_NORM}
#  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_PT_NORM}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_T_RAP_NORM}
  - {dataset: ATLAS_SINGLETOP_TCH_DIFF_8TEV_TBAR_RAP_NORM}
# CMS
- experiment: CMS
  datasets:
  #EWK
  - {dataset: CMSWEASY840PB, frac: 1.0} 
  - {dataset: CMSWMASY47FB, frac: 1.0}
  - {dataset: CMSWCHARMTOT, frac: 1.0}
  - {dataset: CMSWCHARMRAT, frac: 1.0}
  - {dataset: CMS_WCHARM_DIFF_UNNORM_13TEV, frac: 1.0}
  - {dataset: CMSDY2D11, frac: 0.5}
  - {dataset: CMSWMU8TEV, frac: 1.0}
  #Z pt
  - {dataset: CMSZDIFF12, frac: 1.0, cfac: [NRM]}
  #SINGLE JETS
#  - {dataset: CMSJETS11_NEW_SCALE, frac: 0.5, cfac: [EWK]}
#  - {dataset: CMS_1JET_8TEV, frac: 0.5, cfac: [EWK]}
  #DIJETS
  - {dataset: CMS_2JET_7TEV, frac: 0.5, cfac: [EWK]}
  - {dataset: CMS_2JET_3D_8TEV, frac: 0.5, cfac: [EWK]}
  #TOP PAIR
  - {dataset: CMSTTBARTOT, frac: 1.0}
  - {dataset: CMSTTBARTOT5TEV, frac: 1.0}
  - {dataset: CMSTOPDIFF8TEVTTRAPNORM, frac: 1.0}
  - {dataset: CMS_TTBAR_2D_DIFF_MTT_TRAP_NORM, frac: 1.0}
#  - {dataset: CMS_TTBAR_2D_DIFF_MTT_TTRAP_NORM, frac: 1.0}
#  - {dataset: CMS_TTBAR_2D_DIFF_PT_TRAP_NORM, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TPT, frac: 1.0}
  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TRAP, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TTM, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_2L_TTRAP, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TPT, frac: 1.0}
  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TRAP, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TTM, frac: 1.0}
#  - {dataset: CMS_TTB_DIFF_13TEV_2016_LJ_TTRAP, frac: 1.0}
  #SINGLE TOP
  - {dataset: CMS_SINGLETOP_TCH_TOT_7TEV, frac: 1.0}
  - {dataset: CMS_SINGLETOP_TCH_R_8TEV, frac: 1.0}
  - {dataset: CMS_SINGLETOP_TCH_R_13TEV, frac: 1.0}
# LHCb 
- experiment: LHCb
  datasets:
  - {dataset: LHCBZ940PB, frac: 1.0}
  - {dataset: LHCBZEE2FB, frac: 1.0}
  - {dataset: LHCBWZMU7TEV, frac: 1.0, cfac: [NRM]}
  - {dataset: LHCBWZMU8TEV, frac: 1.0, cfac: [NRM]}
  - {dataset: LHCB_Z_13TEV_DIMUON, frac: 1.0}
  - {dataset: LHCB_Z_13TEV_DIELECTRON, frac: 1.0}

############################################################
datacuts:
  t0pdfset: 200101-ern-dijets-nlo    # PDF set to generate t0 covmat
  q2min: 3.49                        # Q2 minimum
  w2min: 12.5                        # W2 minimum
  combocuts: NNPDF31                 # NNPDF3.0 final kin. cuts
  jetptcut_tev: 0                    # jet pt cut for tevatron
  jetptcut_lhc: 0                    # jet pt cut for lhc
  wptcut_lhc: 30.0                   # Minimum pT for W pT diff distributions
  jetycut_tev: 1e30                  # jet rap. cut for tevatron
  jetycut_lhc: 1e30                  # jet rap. cut for lhc
  dymasscut_min: 0                   # dy inv.mass. min cut
  dymasscut_max: 1e30                # dy inv.mass. max cut
  jetcfactcut: 1e30                  # jet cfact. cut

############################################################
theory:
  theoryid: 52        # database id

############################################################
fitting:
  seed: 9453862133528           # set the seed for the random generator
  genrep: on        # on = generate MC replicas, off = use real data
  rngalgo: 0        # 0 = ranlux, 1 = cmrg, see randomgenerator.cc
  fitmethod: NGA    # Minimization algorithm
  ngen: 30000       # Maximum number of generations
  nmutants: 80      # Number of mutants for replica
  paramtype: NN
  nnodes: [2, 5, 3, 1]

  # NN23(QED) = sng=0,g=1,v=2,t3=3,ds=4,sp=5,sm=6,(pht=7)
  # EVOL(QED) = sng=0,g=1,v=2,v3=3,v8=4,t3=5,t8=6,(pht=7)
  # EVOLS(QED)= sng=0,g=1,v=2,v8=4,t3=4,t8=5,ds=6,(pht=7)
  # FLVR(QED) = g=0, u=1, ubar=2, d=3, dbar=4, s=5, sbar=6, (pht=7)
  fitbasis: NN31IC # EVOL (7), EVOLQED (8), etc.
  basis:
      # remeber to change the name of PDF accordingly with fitbasis
      # pos: on for NN squared
      # mutsize: mutation size
      # mutprob: mutation probability
      # smallx, largex: preprocessing ranges
  - {fl: sng, pos: off, mutsize: [15], mutprob: [0.05], smallx: [1.074, 1.186], largex: [
      1.413, 2.742]}
  - {fl: g, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.9421, 1.236], largex: [
      0.1977, 6.226]}
  - {fl: v, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.5313, 0.7112], largex: [
      1.133, 2.841]}
  - {fl: v3, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.2153, 0.5744], largex: [
      1.019, 3.054]}
  - {fl: v8, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.5596, 0.7318], largex: [
      0.638, 3.284]}
  - {fl: t3, pos: off, mutsize: [15], mutprob: [0.05], smallx: [-0.4156, 1.437], largex: [
      1.712, 3.251]}
  - {fl: t8, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.5336, 1.209], largex: [
      1.428, 2.897]}
  - {fl: cp, pos: off, mutsize: [15], mutprob: [0.05], smallx: [0.01973, 1.167], largex: [
      1.459, 7.666]}

############################################################
stopping:
  stopmethod: LOOKBACK  # Stopping method
  lbdelta: 0            # Delta for look-back stopping
  mingen: 0             # Minimum number of generations
  window: 500           # Window for moving average
  minchi2: 3.5          # Minimum chi2 
  minchi2exp: 6.0       # Minimum chi2 for experiments
  nsmear: 200           # Smear for stopping
  deltasm: 200          # Delta smear for stopping
  rv: 2                 # Ratio for validation stopping
  rt: 0.5               # Ratio for training stopping
  epsilon: 1e-6         # Gradient epsilon

############################################################
positivity:
  posdatasets:
  - {dataset: POSF2U, poslambda: 1e6}        # Positivity Lagrange Multiplier
  - {dataset: POSF2DW, poslambda: 1e6}
  - {dataset: POSF2S, poslambda: 1e6}
  - {dataset: POSFLL, poslambda: 1e6}
  - {dataset: POSDYU, poslambda: 1e10}
  - {dataset: POSDYD, poslambda: 1e10}
  - {dataset: POSDYS, poslambda: 1e10}

############################################################
closuretest:
  filterseed: 0     # Random seed to be used in filtering data partitions
  fakedata: off     # on = to use FAKEPDF to generate pseudo-data
  fakepdf: MSTW2008nlo68cl      # Theory input for pseudo-data
  errorsize: 1.0    # uncertainties rescaling
  fakenoise: off    # on = to add random fluctuations to pseudo-data
  rancutprob: 1.0   # Fraction of data to be included in the fit
  rancutmethod: 0   # Method to select rancutprob data fraction
  rancuttrnval: off # 0(1) to output training(valiation) chi2 in report
  printpdf4gen: off # To print info on PDFs during minimization

############################################################
lhagrid:
  nx: 150
  xmin: 1e-9
  xmed: 0.1
  xmax: 1.0
  nq: 50
  qmax: 1e5

############################################################
debug: off