# A CI script with github workflow to regenerate the data
name: Regenerate Commondata

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'regenerate-data')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install NNPDF data package ğŸ
        run: pip install ./nnpdf_data/'[filter]'
      - name: Run the filters ğŸ“¦
        shell: bash -l {0}
        run: |
          here=$PWD
          readarray -d '' array < <(find ./nnpdf_data/nnpdf_data/commondata -name "filter.py" -print0)
          for datname in "${array[@]}"; do dirpath=${datname%/*}; cd $dirpath; python filter.py || exit $?; cd $here; done
      - name: Check for modified files ğŸ›ï¸
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
      - name: Commit the changed files ğŸ›ï¸
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        shell: bash -l {0}
        run: |
          git config user.name "Regenerate Commondata"
          git config user.email "<>"
          git add nnpdf_data/nnpdf_data/commondata/*
          git status
          git commit -m "Automatically regenerated commondata from PR ${{ github.event.number }}, branch ${{ github.event.pull_request.head.ref }}."
          git push origin "${{ github.event.pull_request.head.ref }}"
